project_id = "rkhwacnkhnpxsekvgxtz"

[functions.generate-video]
verify_jwt = false

[functions.process-prompt]
verify_jwt = false

[functions.paddle-webhook]
verify_jwt = false

[functions.renew-credits]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = false
